// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using plataformasGrupo5TPFinal.Data;

namespace plataformasGrupo5TPFinal.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("plataformasGrupo5TPFinal.Models.Cabaña", b =>
                {
                    b.Property<int>("idCabana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("barrio")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("baños")
                        .HasColumnType("int");

                    b.Property<int>("cantPersonas")
                        .HasColumnType("int");

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("codigo")
                        .HasColumnType("int");

                    b.Property<int>("estrellas")
                        .HasColumnType("int");

                    b.Property<int>("habitaciones")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("precioDia")
                        .HasColumnType("real");

                    b.Property<bool>("tv")
                        .HasColumnType("bit");

                    b.HasKey("idCabana");

                    b.ToTable("Cabañas");
                });

            modelBuilder.Entity("plataformasGrupo5TPFinal.Models.Hotel", b =>
                {
                    b.Property<int>("idHotel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("barrio")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("cantPersonas")
                        .HasColumnType("int");

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("codigo")
                        .HasColumnType("int");

                    b.Property<int>("estrellas")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("precioPorPersona")
                        .HasColumnType("real");

                    b.Property<int>("tv")
                        .HasColumnType("int");

                    b.HasKey("idHotel");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("plataformasGrupo5TPFinal.Models.Reservas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("codAlojamiento")
                        .HasColumnType("int");

                    b.Property<int>("dniPersona")
                        .HasColumnType("int");

                    b.Property<DateTime>("fDesde")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("fHasta")
                        .HasColumnType("DateTime");

                    b.Property<float>("precio")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("plataformasGrupo5TPFinal.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bloqueado")
                        .HasColumnType("bit");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<bool>("esAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("intentos")
                        .HasColumnType("int");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
